### ISSUE TITLE
Great Circle Calculator

### ISSUE THREAD

**Issue by WX3K** [VE2ZAZ/VHF_Contest_Logger_Software#2]
Running Ubuntu 22.04.01

Any thoughts on this NameError when running VCL

$ python3 VHF_Contest_QSO_Logger.py
Traceback (most recent call last):
  File "/home/wx3k/Downloads/VCL/VHF_Contest_Logger_Software-main/VHF_Contest_QSO_Logger.py", line 47, in <module>
    sys.path.append("./great_circle_calculator")
NameError: name 'sys' is not defined

**Comment by VE2ZAZ** [comment]
Hi,

In the VHF_Contest_QSO_Logger.py file, just add the following line: 
"import sys"
just above the line "sys.path.append("./great_circle_calculator")".

For a reason I cannot explain, it works without that added import command at my end. But we should always import the sys module if we are going to use it.

Thanks!

Bert.

**Comment by WX3K** [comment]
Hi Bert !

I inserted the "import sys" and reran

python3 VHF_Contest_QSO_Logger.py
Traceback (most recent call last):
  File "/home/wx3k/Downloads/VCL/VHF_Contest_Logger_Software-main/VHF_Contest_QSO_Logger.py", line 49, in <module>
    import great_circle_calculator as gcc
ModuleNotFoundError: No module named 'great_circle_calculator'


Stephanie

**Comment by VE2ZAZ** [comment]
Sorry, I forgot to include the 'great_circle_calculator' directory on GitHub. Some software distribution teething...

 I just uploaded that directory. Please download it and add it inside your program directory where the  "VHF_Contest_QSO_Logger.py" file resides. In the end, it will be a sub-directory to which the python script refers.

Don't worry, you are almost there!

Bert.

**Comment by VE2ZAZ** [comment]
BTW, I will be operating during the January VHF Contest as VA2IW. Hope to work you! Good luck! 73.
Bert.

**Comment by WX3K** [comment]
Bert !

Thank you for the assist. VCL is up and running. Yay !!!!!
I will look for you as VA2IW.

Good luck to you as well

73
Stephanie

**Comment by VE2ZAZ** [comment]
Told you you were close to having it running!
73.
Bert.
