### ISSUE TITLE
Scoring in VCL - QSO Point error

### ISSUE THREAD

**Issue by WX3K** [VE2ZAZ/VHF_Contest_Logger_Software#3]
Statistics gave me 139 QSOs 162 QSO points 49 Multiplers

Submitted log to ARRL gave me 163 QSO points X 49 Multipliers

Not sure where the extra QSO point came from

**Comment by VE2ZAZ** [comment]
Thanks for reporting that. Can you provide your VHFlog logbook file? Send it to ve2zaz@sympatico.ca. I will look into it and let you know the outcome. Scoring is relatively easy to compute, so it makes me wonder...

BTW, I have just added a Cabrillo-to-ADIF file conversion script along with the updated versionversion of the logging program. Very useful if you want to input your QSOs in other logbooks, such as QRZ.com.

Thanks, 73

Bert, VE2ZAZ / VA2IW

**Comment by VE2ZAZ** [comment]
Hi Stephanie,

The missing QSO point came from a bug in taking the January contest point distribution into account. It is 4 points for a 1.2G QSO, vs. 3 points in June or September. I have updated GitHub with version 1.3 of the script.

Thanks for providing feedback!
